In [6]:
import sys
import requests
import pandas as pd
from jobspy import scrape_jobs
from datetime import datetime

In [2]:
sys.version

'3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]'

In [3]:
from jobspy import scrape_jobs

df = scrape_jobs(
    site_name=["linkedin", "indeed"],
    search_term="data analyst",
    location="United States",
    results_wanted=10,
    hours_old=72,
    country_indeed="USA"
)

2026-07-10 22:20:26,931 - INFO - JobSpy:Linkedin - finished scraping

In [4]:
df.shape

(20, 34)

In [5]:
df.head()

,id,site,job_url,job_url_direct,title,company,location,date_posted,job_type,salary_source,...,company_addresses,company_num_employees,company_revenue,company_description,skills,experience_range,company_rating,company_reviews_count,vacancy_count,work_from_home_type
0,in-3d91507511787ce2,indeed,https://www.indeed.com/viewjob?jk=3d9150751178...,https://careers.nordstrom.com/data-analyst-3-t...,Data Analyst 3 - Transportation - HYBRID (Seat...,Nordstrom,"Seattle, WA, US",2026-07-10,NaN,direct_data,...,"Seattle, WA","10,000+",more than $10B (USD),"Nordstrom, Inc. is a leading fashion retailer ...",None,None,None,None,None,None
1,in-9be1f40746b0c193,indeed,https://www.indeed.com/viewjob?jk=9be1f40746b0...,https://www.gdit.com/careers/job/94dfbd37b/pro...,Program/Data Analyst Advisor,General Dynamics Information Technology,"Remote, US",2026-07-10,NaN,direct_data,...,"Falls Church, VA","10,000+",more than $10B (USD),We are GDIT. The people supporting some of the...,None,None,None,None,None,None
2,in-dce7a57d29578d54,indeed,https://www.indeed.com/viewjob?jk=dce7a57d2957...,https://deloitteus.avature.net/careers/InviteT...,Clinical Data Analyst,Deloitte,"Arlington, VA, US",2026-07-10,fulltime,direct_data,...,"New York, NY","10,000+",more than $10B (USD),"We’re a leading professional services firm, bu...",None,None,None,None,None,None
3,in-76f635cd70a114f1,indeed,https://www.indeed.com/viewjob?jk=76f635cd70a1...,https://www.paycomdfw.net/v4/ats/web.php/porta...,Revenue Cycle Business Intelligence (BI) Analyst,GI ALLIANCE,"Southlake, TX, US",2026-07-10,fulltime,NaN,...,"Southlake, TX","5,001 to 10,000",$500M to $1B (USD),NaN,None,None,None,None,None,None
4,in-a19af956925dc87d,indeed,https://www.indeed.com/viewjob?jk=a19af956925d...,https://careers-unitypoint.icims.com/jobs/1844...,Compliance Analyst,UnityPoint Health,"Madison, WI, US",2026-07-10,fulltime,NaN,...,NaN,"10,000+",Decline to state,We're proud to be recognized as a Top Place to...,None,None,None,None,None,None

In [7]:
API_KEY = "WYvjQd/FlCzygwHh1hQ9bjEWflR+6GhiiVEFIpvrT+o="
EMAIL   = "a.battini@myemail.indwes.edu"

In [18]:
KEYWORDS = [# Data & Analytics
            "data analyst", "data engineer", "data scientist", "business analyst",
            "business intelligence analyst", "analytics engineer", "quantitative analyst",
            
            # Engineering & Development  
            "software engineer", "cloud engineer", "DevOps engineer",
            "machine learning engineer", "AI engineer",
            
            # IT & Systems
            "IT specialist", "systems analyst", "database administrator",
            "network engineer", "cybersecurity analyst",
            
            # Management & Operations
            "program analyst", "project manager", "operations analyst"]

In [19]:
## USA JOBS

def fetch_usajobs(keyword):
    headers = {
        "Authorization-Key": API_KEY,
        "User-Agent": EMAIL,
        "Host": "data.usajobs.gov"
    }
    r = requests.get(
        "https://data.usajobs.gov/api/search",
        headers=headers,
        params={"Keyword": keyword, "ResultsPerPage": 50}
    )
    items = r.json()["SearchResult"]["SearchResultItems"]
    rows = []
    for item in items:
        d = item["MatchedObjectDescriptor"]
        rows.append({
            "source":           "USAJobs",
            "search_keyword":   keyword,
            "job_id":           d.get("PositionID", ""),
            "title":            d.get("PositionTitle", ""),
            "company":          d.get("OrganizationName", ""),
            "department":       d.get("DepartmentName", ""),
            "location":         ", ".join([l.get("LocationName", "") for l in d.get("PositionLocation", [])]),
            "salary_min":       d.get("PositionRemuneration", [{}])[0].get("MinimumRange", None),
            "salary_max":       d.get("PositionRemuneration", [{}])[0].get("MaximumRange", None),
            "salary_interval":  d.get("PositionRemuneration", [{}])[0].get("RateIntervalCode", None),
            "posted_date":      d.get("PublicationStartDate", "")[:10],
            "close_date":       d.get("ApplicationCloseDate", "")[:10],
            "job_url":          d.get("PositionURI", ""),
            "job_summary":      d.get("UserArea", {}).get("Details", {}).get("JobSummary", "")[:500],
            "work_schedule":    d.get("PositionSchedule", [{}])[0].get("Name", ""),
            "position_type":    d.get("PositionOfferingType", [{}])[0].get("Name", ""),
            "security_clearance": d.get("UserArea", {}).get("Details", {}).get("SecurityClearance", ""),
            "remote":           None,
            "collected_at":     datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
        })
    return rows

In [28]:
headers = {
        "Authorization-Key": API_KEY,
        "User-Agent": EMAIL,
        "Host": "data.usajobs.gov"
    }
r = requests.get(
        "https://data.usajobs.gov/api/search",
        headers=headers,
        params={"Keyword": keyword, "ResultsPerPage": 50})
items = r.json()["SearchResult"]["SearchResultItems"]
items[0]

{'MatchedObjectId': '875687900',
 'MatchedObjectDescriptor': {'PositionID': '26-BPA-51990-13001036-BPA',
  'PositionTitle': 'Market and Pricing Analyst (Operations Research Analyst)',
  'PositionURI': 'https://www.usajobs.gov:443/job/875687900',
  'ApplyURI': ['https://www.usajobs.gov:443/job/875687900'],
  'PositionLocationDisplay': 'Portland, Oregon',
  'PositionLocation': [{'LocationName': 'Portland, Oregon',
    'CountryCode': 'United States',
    'CountrySubDivisionCode': 'Oregon',
    'CityName': 'Portland, Oregon',
    'Longitude': -122.67563,
    'Latitude': 45.511795}],
  'OrganizationName': 'Bonneville Power Administration',
  'DepartmentName': 'Department of Energy',
  'JobCategory': [{'Name': 'Operations Research', 'Code': '1515'}],
  'JobGrade': [{'Code': 'GS'}],
  'PositionSchedule': [{'Name': '', 'Code': '1'}],
  'PositionOfferingType': [{'Name': '', 'Code': '15317'}],
  'QualificationSummary': 'BASIC REQUIREMENTS: Degree: in operations research; or at least 24 semester hours in a combination of operations research, mathematics, probability, statistics, mathematical logic, science, or subject-matter courses requiring substantial competence in college-level mathematics or statistics. At least 3 of the 24 semester hours must have been in calculus. SPECIALIZED EXPERIENCE REQUIREMENTS: A qualified candidate\'s resume must demonstrate at least one year of specialized experience equivalent to the next lower grade level (GS-12) in the Federal service. Specialized experience for this position is defined as experience 1) developing and utilizing computer models to analyze factors affecting electrical power systems, such as market fundamentals, resource operations, or price forecasting; 2) providing data-driven reports and recommendations to management or subject matter experts; and 3) Conducting economic/financial analyses of utility-scale energy generation resources or wholesale power contracts to evaluate portfolio costs and performance. There is no substitution of education for experience at the GS-13 grade level. "Experience" refers to paid and unpaid experience. Examples of qualifying unpaid experience may include: volunteer work done through National Service programs (such as Peace Corps and AmeriCorps); as well as work for other community-based philanthropic and social organizations. Volunteer work helps build critical competencies, knowledge, and skills; and can provide valuable training and experience that translates directly to paid employment. You will receive credit for all qualifying experience, including volunteer experience. Time-in-Grade: Current Federal employees must meet time-in-grade requirements by the closing date of this announcement to receive consideration. CTAP candidates: To be considered "well qualified" you must meet all of the requirements as described in this section. You must meet all qualifications and eligibility requirements by the closing date of this announcement.',
  'PositionRemuneration': [{'MinimumRange': '114684',
    'MaximumRange': '149091',
    'RateIntervalCode': 'PA',
    'Description': 'Per Year'}],
  'PositionStartDate': '2026-07-08T10:09:58.9730',
  'PositionEndDate': '2026-07-17T23:59:59.9970',
  'PublicationStartDate': '2026-07-08T10:09:58.9730',
  'ApplicationCloseDate': '2026-07-17T23:59:59.9970',
  'PositionFormattedDescription': [{'Label': 'Dynamic Teaser',
    'LabelDescription': 'Hit highlighting for keyword searches.'}],
  'UserArea': {'Details': {'JobSummary': "This position is located with Bonneville Power Administration (BPA), in Market Analysis & CAISO Settlements (PTMA) organization in Market Analysis and Pricing (PTM) group, Bulk Marketing (PT), Power Services (P). A successful candidate in the Market and Pricing Analyst (Operations Research Analyst) position will serve as a senior analyst of energy market fundamentals to support BPA policy decisions, influence marketing strategies, and inform BPA's power operations.",
    'WhoMayApply': {'Name': '', 'Code': ''},
    'LowGrade': '13',
    'HighGrade': '13',
    'PromotionPotential': 'None',
    'OrganizationCodes': 'DN/DN03',
    'Relocation': 'False',
    'HiringPath': ['fed-internal-search'],
    'MCOTags': [],
    'TotalOpenings': '1',
    'AgencyMarketingStatement': "We are truly honored that DOE has been named America's #1 Best Employer for Veterans in 2023 by Forbes-not only among Government agencies, but among employers across the U.S. We are so proud of this ranking which reflects our commitment to the employment of veterans. As so many veterans at DOE renew their service to our Nation, we are deeply committed to their success and advancement. Veterans shape the future of energy The Bonneville Power Administration is a nonprofit federal power marketing administration based in the Pacific Northwest. Although BPA is part of the U.S. Department of Energy, it is self-funding and covers its costs by selling its products and services. BPA markets wholesale electrical power from 31 federal hydroelectric projects in the Northwest, one nonfederal nuclear plant and several small nonfederal power plants. This position is located in Portland, OR which boasts huge spans of amazing trees, foliage, landscape, and everywhere you look you can appreciate beautiful greenery! It is known as the most bike-friendly city in America, has a train system that greets you at the airport spanning across the city, and is home to the Portland International Rose Garden, the oldest in the country! Portland is the one place where you will find lively festivals, energetic music, mouthwatering food, and for you basketball fans, the Portland Trail Blazers are a 7 minute walk from the HQs building! There is always something new to experience in this eco-friendly town!?",
    'TravelCode': '1',
    'ApplyOnlineUrl': 'https://apply.usastaffing.gov/Application/Apply',
    'DetailStatusUrl': 'https://apply.usastaffing.gov/Application/ApplicationStatus',
    'MajorDuties': ['As a Operations Research Analyst, you will: Independently conduct or lead research into energy market fundamentals and policy initiatives in the Pacific Northwest, West Coast, and nationally to address economic, strategy and policy questions. Lead the development of experimental approaches to determining total power portfolio benefit/costs based on projected operational and market strategies. This includes the economic evaluation of the impacts from different power system operations, different levels and types of power sales or purchases, and different levels and types of additional balancing capacity need to cost effectively support the integration of variable generation resources. Lead analysis required to implement complex contracts or support BPA policy decisions (i.e. Pacific NW Coordination Agreement, Non-treaty Storage, Contracts with optionality, etc.) Serve as a subject matter expert on teams responsible for the development and production of analytical studies. Maintain contact and work collaboratively with Power Services employees, corporate employees, and consultants as needed. Communicate verbally and in writing on assigned responsibilities, including technical studies and project reports.'],
    'Education': "This vacancy has a positive education requirement. In order to be rated as qualified, you must provide copies of your college transcripts. Education must be obtained from an accredited institution recognized by the U.S. Department of Education. See Department of Education Accreditation Search to verify school accreditation. Foreign education must be reviewed by an organization recognized by the U.S. Department of Education. For special instructions pertaining to foreign education and a list of organizations that can evaluate foreign education, see the Department of Education website.DO NOT email or mail in any of your application documents. Documents will not be accepted outside of the online application system. Failure to provide college transcripts may result in a rating of 'Ineligible'.",
    'Requirements': 'In accordance with Executive Order 14170, applicants are encouraged to respond to four short, free-response, essay questions in the questionnaire. Answer to these questions is not scored or rated. Your answers will be reviewed by the hiring manager and agency leadership if you are referred for selection consideration. When you apply you will be asked a series of questions to determine your eligibility for employment and your qualification for this position specifically. You must answer all of these questions completely and truthfully. Key Requirements: You must be a United States Citizen. This employer participates in the e-Verify program. Males must abide by Selective Service registration requirements. You will be required to report in person to the official duty location. Additional Information: Position has supervisory functions.',
    'Evaluations': 'You will be evaluated for this job based on how well you meet the eligibility and qualification requirements above. Once the announcement closes, we will conduct a review of your application package to verify your eligibility and qualifications. If you are found qualified, your application will move forward to additional phases of the review process. Minimum Qualifications: Once the application process is complete, the Human Resources Offices or Subject Matter Expert (SME) will review your two-page resume and supporting documentation to determine whether you meet the minimum job qualifications. Selection will be based on skills and competencies, not educational credentials or self-reported experience. Merit Promotion & VEOA Procedures: If you are minimally qualified for this job, your will be assessed and evaluated to determine if you are a best qualified candidate. Federal employees must meet time-in-grade requirements and current employees must have at least a fully successful or equivalent performance rating to receive consideration. Your qualifications will be evaluated on the following competencies (knowledge, skills, abilities, and other characteristics): Arithmetic/Mathematical Reasoning Attention to Detail Customer Service Decision Making Flexibility Integrity/Honesty Interpersonal Skills Learning Reasoning Self-Management Stress Tolerance Teamwork Career Transition Assistance Programs: To receive selection priority for this position, you must: 1) meet the eligibility criteria; and 2) be rated "well-qualified", which is defined as having a score of 85 or better. You must meet all qualifications and eligibility requirements by the closing date (07/17/2026) of this announcement. To preview the Assessment Questionnaire, click https://apply.usastaffing.gov/ViewQuestionnaire/13001036 USAHire: To be considered for this position, you must complete all required steps in the process. In addition to the application and application questionnaire, this position requires an online assessment. The online assessment measures critical general competencies required to perform the job.',
    'HowToApply': 'Please read the entire announcement and all the instructions before you begin an application. To apply for this position, you must complete the initial online application, to include submission of the required documentation specified in the Required Documents section. A complete application package must be submitted by 11:59 PM (EST) on the announcement closing date to receive consideration. The application process is as follows: You must have a login.gov account to sign into USAJOBS: https://help.usajobs.gov/how-to/account. To begin the application process in USAJOBS, click the Apply Online button. Answer the questions presented in the application and attach all required and supporting documentation. You must click the Submit Application button prior to 11:59 pm (ET) on the announcement closing date. After submitting an online application, you will be notified whether or not you are required to take additional online assessments through the USA Hire Competency Based Assessment system. This message will be delivered to you via email notification. The email may be routed to your "Spam" or "Junk" folder. If you are asked to take the USA Hire Competency Based Assessments, you will be presented with a unique URL to access the USA Hire system. Access to USA Hire is granted through your USAJOBS login credentials. Be sure to review all instructions prior to beginning your USA Hire Assessments. Click here for Computer System Requirements Note, set aside at least 3 hours to take these assessments; however, most applicants complete the assessments in less time. If you need to stop the assessments and continue at a later time, you can reuse the URL sent to you via email and also found in your USAJOBS account under the "Track my application" link for the corresponding application. You may update your application, including supporting documentation, at any time during the announcement open period by returning to your USAJOBS account, select Update Application: https://login.usajobs.gov/Account/Login. This option will no longer be available once the announcement has closed. To verify the status of your application, during and after the announcement open period, log into your USAJOBS account; applications will appear on the Welcome screen. The Application Status will appear along with the date your application was last updated. For information on what each application status means, visit: https://help.usajobs.gov/how-to/application/status. If you need help with login.gov or USAJOBS (e.g., account access, Resume Builder) visit the USAJOBS Help Center: https://help.usajobs.gov/how-to If you experience difficulty applying on USAJOBS, after clicking the Apply Online button, or you are experiencing a significant hardship hindering your ability to apply online, the Agency Contact listed in the announcement can assist you during normal business hours. If you receive any system error messages, take screenshots if possible, to aid technical support.',
    'WhatToExpectNext': 'Based on your application and your responses to the application questionnaire, you may be presented with instructions on how to access the USA Hire system to complete the online assessments. The online assessments must be completed within 48 hours following the close of this announcement. You will have the opportunity to request a testing accommodation for the assessment should you have a disability covered under the Rehabilitation Act of 1973 as amended. Your assessment results will be kept on record for one year and used toward future positions for which you might apply that require the same assessments. Once your online application is submitted you will receive a confirmation notification by email. The status of your application will be updated in USAJOBS as it is evaluated. You can check the status by logging into USAJOBS. You may also sign up to receive automatic emails anytime the status of your application changes by logging into your USAJobs Account and editing the Notification Settings. You will be contacted directly if an interview is required.',
    'RequiredDocuments': 'To apply for this position, you MUST provide a complete application package which includes: Your two (2) page RESUME showing all relevant work experience (paid and unpaid) including: duties performed; full name and address of each employer; start and end dates (month/day/year); work schedule (part-time, full-time, number of hours if intermittent); salary; and any completed education and training (program title, subject area, number of hours completed, and completion date). Information on how to create a federal resume https://help.usajobs.gov/how-to/account/documents/resume Cover Letter, optional, expressing additional information not covered in your resume. Transcripts, if specific educational requirements are indicated in this job announcement. Unofficial transcripts or any report listing institution, course title, credits earned (semester or quarter hour) and final grade is acceptable. It is your responsibility to provide adequate proof that you meet the educational requirements. Submit one or more of the following to support your eligibility(s) to apply to this job announcement: SF-50, "Notification of Personnel Action" (current/former federal employees): Most recent Promotion, Within Rate Increase (WRI/WGI), or Appointment/Conversion SF-50 or Notification of Personnel Action showing you are/were in the competitive service and the highest grade or promotion potential held. Career Transition Assistance Program/Interagency Career Transition Assistance Program documentation, if applicable (e.g., Certification of Expected Separation, Reduction-In-Force Separation Notice, or Notice of Proposed Removal; SF-50 that documents the RIF separation action; and most recent performance appraisal.) For more information see the OPM Guide to Career Transition. Failure to submit any of the above mentioned required documents may result in loss of consideration due to an incomplete application package. It is your responsibility to ensure all required documents have been submitted. If selected for the position you MUST submit: A copy of your most recent performance appraisal/evaluation and incentive awards, you received in the last 5 years. The assigned HR Specialist will verify review this documentation to ensure selectee has at least a satisfactory performance rating before setting the entrance on duty date. If you do not have your most recent performance appraisal/evaluation, you will be asked to submit a statement as to why it is not available.',
    'Benefits': '',
    'BenefitsUrl': 'https://help.usajobs.gov/index.php/Pay_and_Benefits',
    'BenefitsDisplayDefaultText': True,

In [30]:
df = scrape_jobs(
            site_name=["linkedin", "indeed"],
            search_term=keyword,
            location="United States",
            results_wanted=5,
            hours_old=24,
            country_indeed="USA")

df.head()

,id,site,job_url,job_url_direct,title,company,location,date_posted,job_type,salary_source,...,company_addresses,company_num_employees,company_revenue,company_description,skills,experience_range,company_rating,company_reviews_count,vacancy_count,work_from_home_type
0,in-566c5831fcb520e0,indeed,https://www.indeed.com/viewjob?jk=566c5831fcb5...,https://www.paycomonline.net/v4/ats/web.php/po...,Direct Support Prof 2 - 1260,Central Counties Services,US,2026-07-10,fulltime,NaN,...,NaN,NaN,NaN,NaN,None,None,None,None,None,None
1,in-b332550ca98bc9b1,indeed,https://www.indeed.com/viewjob?jk=b332550ca98b...,https://ecvz.fa.us2.oraclecloud.com/hcmUI/Cand...,EHR Certified Systems Analyst II,Adventist Health,"Roseville, CA, US",2026-07-10,fulltime,direct_data,...,NaN,NaN,NaN,NaN,None,None,None,None,None,None
2,in-4c983e7a02ede5dc,indeed,https://www.indeed.com/viewjob?jk=4c983e7a02ed...,https://www.paycomonline.net/v4/ats/web.php/po...,Information Technology Support Specialist,NaN,"Colorado Springs, CO, US",2026-07-10,fulltime,direct_data,...,NaN,NaN,NaN,NaN,None,None,None,None,None,None
3,in-05452d517d484970,indeed,https://www.indeed.com/viewjob?jk=05452d517d48...,https://workforcenow.adp.com/mascsr/default/md...,Systems and Marketing Analyst,SUN COMMUNITY FEDERAL CREDIT U,"El Centro, CA, US",2026-07-10,fulltime,direct_data,...,NaN,NaN,NaN,NaN,None,None,None,None,None,None
4,in-d2422b595543b14b,indeed,https://www.indeed.com/viewjob?jk=d2422b595543...,https://jsv3.recruitics.com/redirect?rx_cid=35...,Director of ABA Services,ABS Kids,"Columbia, SC, US",2026-07-09,fulltime,direct_data,...,"Encino, CA","1,001 to 5,000",$100M to $500M (USD),To empower children with autism spectrum disor...,None,None,None,None,None,None

In [20]:
## LINKDIN & INDEED

def fetch_web_jobs(keyword):
    try:
        df = scrape_jobs(
            site_name=["linkedin", "indeed"],
            search_term=keyword,
            location="United States",
            results_wanted=50,
            hours_old=168,
            country_indeed="USA"
        )
        rows = []
        for _, r in df.iterrows():
            rows.append({
                "source":           str(r.get("site", "")).title(),
                "search_keyword":   keyword,
                "job_id":           str(r.get("id", "")),
                "title":            r.get("title", ""),
                "company":          r.get("company", ""),
                "department":       None,
                "location":         r.get("location", ""),
                "salary_min":       r.get("min_amount", None),
                "salary_max":       r.get("max_amount", None),
                "salary_interval":  r.get("interval", None),
                "posted_date":      str(r.get("date_posted", ""))[:10],
                "close_date":       None,
                "job_url":          r.get("job_url", ""),
                "job_summary":      str(r.get("description", ""))[:500],
                "work_schedule":    str(r.get("job_type", "")),
                "position_type":    None,
                "security_clearance": None,
                "remote":           r.get("work_from_home_type", None),
                "collected_at":     datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
            })
        return rows
    except Exception as e:
        print(f"  Error scraping '{keyword}': {e}")
        return []

In [21]:
all_rows = []
seen_ids = set()

for keyword in KEYWORDS:
    
    usa_rows = fetch_usajobs(keyword)
    for row in usa_rows:
        uid = f"usajobs_{row['job_id']}"
        if uid not in seen_ids:
            seen_ids.add(uid)
            all_rows.append(row)
    
   
    web_rows = fetch_web_jobs(keyword)
    for row in web_rows:
        uid = f"{row['source']}_{row['job_id']}"
        if uid not in seen_ids:
            seen_ids.add(uid)
            all_rows.append(row)

df_combined = pd.DataFrame(all_rows)

In [22]:
df_combined.shape

(2124, 19)

In [23]:
df_combined['source'].value_counts()

source
Linkedin    962
Indeed      673
USAJobs     489
Name: count, dtype: int64

In [24]:
import os

In [25]:
os.makedirs("data", exist_ok=True)

date_str = datetime.utcnow().strftime("%Y%m%d")
filename = f"data/jobs_combined_{date_str}.csv"

df_combined.to_csv(filename, index=False)

In [26]:
df_combined.columns

Index(['source', 'search_keyword', 'job_id', 'title', 'company', 'department',
       'location', 'salary_min', 'salary_max', 'salary_interval',
       'posted_date', 'close_date', 'job_url', 'job_summary', 'work_schedule',
       'position_type', 'security_clearance', 'remote', 'collected_at'],
      dtype='object')